# Generate .env with secrets for local development (no Docker)
$ErrorActionPreference = "Stop"
$Root = Split-Path $PSScriptRoot -Parent
$EnvFile = Join-Path $Root ".env"

if (Test-Path $EnvFile) {
    Write-Host ".env already exists - skip (delete to regenerate)" -ForegroundColor Yellow
    exit 0
}

$VenvPython = Join-Path $Root "api\.venv\Scripts\python.exe"
if (-not (Test-Path $VenvPython)) {
    Write-Host "Run setup-local.ps1 first (missing api\.venv)" -ForegroundColor Red
    exit 1
}

$jwt = & $VenvPython -c "import secrets; print(secrets.token_hex(32))"
$fernet = & $VenvPython -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
$redisPw = & $VenvPython -c "import secrets; print(secrets.token_hex(32))"
$pepper = & $VenvPython -c "import secrets; print(secrets.token_hex(32))"
$pubsub = & $VenvPython -c "import secrets; print(secrets.token_hex(32))"
$mappingsDir = (Join-Path $Root "db\mappings") -replace '\\', '/'

$lines = @(
    "# Local development (no Docker) - generated by scripts/generate-env.ps1"
    "POSTGRES_USER=sentry"
    "POSTGRES_PASSWORD=sentry"
    "POSTGRES_DB=sentry"
    ""
    "DATABASE_URL=postgresql://sentry:sentry@localhost:5432/sentry"
    "FLASK_ENV=development"
    "FLASK_PORT=5000"
    ""
    "JWT_SECRET=$jwt"
    "SENTRY_ENCRYPTION_KEY=$fernet"
    "REDIS_PASSWORD=$redisPw"
    "SENTRY_TOKEN_PEPPER=$pepper"
    "SENTRY_PUBSUB_HMAC_KEY=$pubsub"
    ""
    "POSTGRES_SUPERUSER=postgres"
    "POSTGRES_SUPERUSER_PASSWORD=postgres"
    ""
    "CORS_ORIGINS=http://localhost:3000,http://localhost:5000,http://localhost:8080"
    "API_BIND_HOST=127.0.0.1"
    "TRUST_PROXY=false"
    ""
    "DISPATCHER_ENABLED=false"
    "CONNECTOR_PUBLISHER_ENABLED=false"
    ""
    "SENTRY_INBOUND_MAPPINGS_DIR=$mappingsDir"
    "ADMIN_PASSWORD=admin"
)

$lines | Set-Content -Path $EnvFile -Encoding UTF8
Write-Host "Created $EnvFile" -ForegroundColor Green
Write-Host "Edit POSTGRES_SUPERUSER_PASSWORD if your postgres password differs."
